services:
  oskari:
    build: ..
    volumes:
      - "./logs/oskari:/log:rw"
    ports:
      - "8080:8080"
    environment:
      OSKARI_OSKARI_PROFILES: 'TreUsernameFilter'

  #    depends_on:
#y      - postgres
  postgres:
    image: docker.io/postgis/postgis:17-3.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=supersalainen_oskarin_salasana
      - POSTGRES_USER=oskari
      - POSTGRES_DB=oskari
    volumes:
      - "./logs/postgres:/log:rw"
      - "./data:/var/lib/postgresql/data"
      - "./pg-initscripts/:/docker-entrypoint-initdb.d/:ro"
