
name: 02 - Build backend image

on:
  workflow_dispatch:

jobs:
  create-backend-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      actions: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'


      - name: Extract release version
        working-directory: server
        run: |
          export BACKEND_VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout |  sed 's/^\(.*\)-SNAPSHOT/\1/')";
          echo "BACKEND_VERSION=${BACKEND_VERSION}" >> $GITHUB_ENV
          echo "Releasing version: ${BACKEND_VERSION}"

      - name: Prepare release
        working-directory: backend
        run:  mvn --no-transfer-progress --batch-mode release:prepare

      - name: Execute release
        working-directory: backend
        run: mvn --no-transfer-progress --batch-mode release:perform -Darguments="-Dmaven.deploy.skip=true" -Dusername=${{env.GIT_USER}}


      # Github packages requires a mandatory login, but becouse the dependency
      # packages are public, we can use GITHUB_TOKEN from this action
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
                "id": "ubigu-github-oskari-server",
                "username": "ignored",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]

      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: 'oskari-frontend-*.tar.gz'
          out-file-path: './backend/'

      # Start the build of dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}


      - name: 'override dockerignore'
        working-directory: ./backend
        run: echo -e '*\n!docker/**\n!webapp-map/target/*' > .dockerignore

#########################################
## Build production
#########################################
      - name: "Unzip the frontend to correct location"
        working-directory: ./backend
        run: mkdir -p ./webapp-map/src/main/webapp/Oskari/ && tar -xz -C ./webapp-map/src/main/webapp/Oskari/ -f ./oskari-frontend*-prod.tar.gz

      - name: "Extract frontend version"
        working-directory: ./backend
        run: echo "FRONTEND_VERSION=$(ls ./webapp-map/src/main/webapp/Oskari/dist)" >> $GITHUB_ENV

      - name: build package
        working-directory: ./backend
        run: mvn --batch-mode package

      - name: 'Extract metadata (tags, labels) for production'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest
            ${{env.BACKEND_VERSION }}

      - name: 'Build and push production Docker image'
        id: push
        uses: docker/build-push-action@v6
        with:
          context: backend
          build-args:
            FRONTEND_VERSION=${{env.FRONTEND_VERSION}}
            OSKARI_CONTEXT=oskari
          file: ./backend/docker/github.Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

####################################
## Build oskaritest
## This can be removed when all oskari instances run in '/oskari' path.
####################################
      - name: "Unzip the frontend to correct location"
        working-directory: ./backend
        run: mkdir -p ./webapp-map/src/main/webapp/Oskari/ && tar -xz -C ./webapp-map/src/main/webapp/Oskari/ -f ./oskari-frontend*-test.tar.gz

      - name: "Extract frontend version"
        working-directory: ./backend
        run: echo "FRONTEND_VERSION=$(ls ./webapp-map/src/main/webapp/Oskari/dist)" >> $GITHUB_ENV

      - name: build package
        working-directory: ./backend
        run: mvn --batch-mode package

      - name: 'Extract metadata (tags, labels) for production'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest-oskaritest
            ${{env.BACKEND_VERSION }}-oskaritest

      - name: 'Build and push production Docker image'
        id: push
        uses: docker/build-push-action@v6
        with:
          context: backend
          build-args:
            FRONTEND_VERSION=${{env.FRONTEND_VERSION}}
            OSKARI_CONTEXT=oskaritest
          file: ./backend/docker/github.Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}