name: Build and release frontend package

on:
  workflow_dispatch:

  push:
    tags:
      - "frontend-*"

permissions:
  contents: write

jobs:
  build-dist-packages:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Install Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: 'Define frontend version'
        run: echo "FRONTEND_VERSION=$(echo "${{ github.ref_name }}" | sed -E 's/[^0-9]*(.*)$/\1/')" >> "$GITHUB_ENV"

      - name: 'Force tag to package version'
        working-directory: ./frontend/
        run: npm version $${{ env.FRONTEND_VERSION }}|| echo "Version already correct"

      - name: 'Install dependencies'
        working-directory: ./frontend/
        run: npm install

      - name: 'Build frontend'
        working-directory: ./frontend/
        run: npm run build

      - name: 'Run Package dist'
        run: tar -czf oskari-${{ github.ref_name }}.tar.gz -C ./frontend/ dist

      - name: "Release zipped images"
        uses: softprops/action-gh-release@v2
        with:
          files: |
            oskari-${{ github.ref_name }}.tar.gz
