name: Build and release frontend package

on:
  push:
    tags:
      - "frontend-*"

permissions:
  contents: write

jobs:
  build-dist-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Define frontend version'
        run: echo "FRONTEND_VERSION=$(echo "${{ github.ref_name }}" | sed -E 's/[^0-9]*(.*)$/\1/')" >> "$GITHUB_ENV"
      - name: 'Force tag to package version'
        working-directory: ./frontend/
        run: npm version $${{ env.FRONTEND_VERSION }}|| echo "Version already correct"

      # Create a gzip file containing the built frontend
      - name: 'Build production Inventory Image'
        working-directory: ./frontend/
        run: |
          docker build ./ --target buildimage --tag ubigu-${{ github.ref_name }} --build-arg BUILD_TARGET=build
      - name: 'Extract production gzip'
        run: |
          id=$(docker create ubigu-${{ github.ref_name }})
          docker cp $id:/opt/oskari/dist - | gzip > oskari-${{ github.ref_name }}.tar.gz
          docker rm -v $id
      - name: "Release zipped images"
        uses: softprops/action-gh-release@v2
        with:
          files: |
            oskari-${{ github.ref_name }}.tar.gz
