name: Cache maven packages on master
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to build the cache from'
        required: true
        type: string

jobs:
  cache-maven-packages:
    name: 'Master cache'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        with:
          ref: refs/tags/${{ inputs.tag_name }}
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Github packages requires a mandatory login, but becouse the oskari-server under ubigu is a public
      # Project, we can use GITHUB_TOKEN from this action
      - uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
              [{
                  "id": "github-oskari-server",
                  "username": "ignored",
                  "password": "${{ secrets.GITHUB_TOKEN }}"
              }]

      - name: 'Fetch dependencies for cache'
        working-directory: ./backend
        run: mvn --batch-mode dependency:resolve dependency:resolve-plugins --fail-never

